import { EarthLocation } from "@/types/scene";

export const EARTH_MOUNTAIN_LANDMARKS: EarthLocation[] = [
  {
    id: "matterhorn",
    name: "Matterhorn Peak",
    region: "Pennine Alps, Zermatt",
    country: "Switzerland",
    lat: 45.9765,
    lng: 7.6585,
    altitude: 4478,
    peakElevation: 4478,
    tag: "ALPINE ICON",
    description: "Iconic pyramidal peak towering over Zermatt with sheer rock facets and glacial ridges.",
    thumbnailUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=600&q=80",
    roughness: 0.95,
    elevationScale: 42,
  },
  {
    id: "mont_blanc",
    name: "Mont Blanc Massif",
    region: "Chamonix Valley",
    country: "France / Italy",
    lat: 45.8326,
    lng: 6.8652,
    altitude: 4808,
    peakElevation: 4808,
    tag: "HIGHEST ALPINE",
    description: "The highest mountain in the Alps, featuring permanent snow caps and dramatic granite needles.",
    thumbnailUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=600&q=80",
    roughness: 0.88,
    elevationScale: 46,
  },
  {
    id: "mount_fuji",
    name: "Mount Fuji",
    region: "Honshu Island",
    country: "Japan",
    lat: 35.3606,
    lng: 138.7274,
    altitude: 3776,
    peakElevation: 3776,
    tag: "VOLCANIC CONE",
    description: "Sacred stratovolcano renowned for its exceptionally symmetrical conical shape and snow summit.",
    thumbnailUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=600&q=80",
    roughness: 0.65,
    elevationScale: 36,
  },
  {
    id: "yosemite_half_dome",
    name: "Half Dome, Yosemite",
    region: "Sierra Nevada, California",
    country: "United States",
    lat: 37.7459,
    lng: -119.5332,
    altitude: 2694,
    peakElevation: 2694,
    tag: "GRANITE CLIFF",
    description: "Monolithic granite crest rising steeply over Yosemite Valley with near-vertical 600m dropoffs.",
    thumbnailUrl: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?auto=format&fit=crop&w=600&q=80",
    roughness: 0.82,
    elevationScale: 34,
  },
  {
    id: "dolomites_tre_cime",
    name: "Tre Cime di Lavaredo",
    region: "Sexten Dolomites",
    country: "Italy",
    lat: 46.6186,
    lng: 12.3028,
    altitude: 2999,
    peakElevation: 2999,
    tag: "LIMESTONE PINNACLES",
    description: "Three distinctive battlement-like peaks of dolomite limestone with steep scree fields.",
    thumbnailUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    roughness: 0.92,
    elevationScale: 39,
  },
  {
    id: "mount_everest",
    name: "Mount Everest (Sagarmatha)",
    region: "Mahalangur Himal",
    country: "Nepal / Tibet",
    lat: 27.9881,
    lng: 86.9250,
    altitude: 8848,
    peakElevation: 8848,
    tag: "ROOF OF THE WORLD",
    description: "Earth's highest peak above sea level, surrounded by massive icefalls and sheer southern faces.",
    thumbnailUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=600&q=80",
    roughness: 0.98,
    elevationScale: 52,
  },
];

export function getLandmarkById(id: string): EarthLocation {
  return EARTH_MOUNTAIN_LANDMARKS.find((m) => m.id === id) || EARTH_MOUNTAIN_LANDMARKS[0];
}
